version: '3.9'
services:
  backend:
    build: ./etl
    stdin_open: true
    tty: true
    volumes:
      - .:/etl
    depends_on:
      - db

  db:
    image: mysql:5.7.37
    restart: always
    environment:
      MYSQL_DATABASE: metrobus_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  api:
    build: ./api
    stdin_open: true
    tty: true
    volumes:
      - .:/api
    ports:
      - 5000:5000
    depends_on:
      - db
